### ISSUE TITLE
补充使用说明

### ISSUE THREAD

**Issue by 123Daoxyz** [hpyer/aliyun-sts#1]
hello，谢谢lz的sdk。瞄了下阿里云的sts sdk，完全不走composer的要求来封装，无语了。

不知道lz能不能基于目前的代码，写一些简单的教程呢？

**Comment by hpyer** [comment]
其实你参照官方给的 [示例](https://help.aliyun.com/document_detail/28791.html?spm=5176.doc28758.6.707.XkD4nr) 就可以了，注释掉示例中的use，改成下面几行就可以
```
use Sts\AssumeRoleRequest;
use Sts\Core\DefaultAcsClient;
use Sts\Core\Profile\DefaultProfile;
```
